spring:
  application:
    name: eswork
  main:
    allow-bean-definition-overriding: true
server:
  port: 8090
  connection-timeout: 1000ms

# elasticsearch配置
elasticsearch:
  clustername: dev-wogame
  node1:
    name: node-1
    address: 192.168.52.111
    port: 9301
  node2:
    name: node-2
    address: 192.168.52.111
    port: 9302
  node3:
    name: node-3
    address: 192.168.52.111
    port: 9303
