server:
  port: 8888
#spring
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: salary
  #mysql
  datasource:
     url: jdbc:mysql://localhost:3306/salary?useUnicode=true&characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml